name: gitlab-action

on:
  push:
    branches: 
      - gitlab
  pull_request:
    branches:
      - gitlab

jobs:
  test:
    runs-on: ubuntu-latest
    name: gitlab-test
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
    - name: test
      id: test
      uses: orgacomp/actions@gitlab-action
      with:
        target: 'test'
