name: combinacionales-action

on:
  push:
    branches: 
      - combinacionales
  pull_request:
    branches:
      - combinacionales

jobs:
  test:
    runs-on: ubuntu-latest
    name: combinacionales-test
    steps:
    - name: checkout
      uses: actions/checkout@v3.3.0
    - name: test
      id: test
      uses: orgacomp/actions@combinacionales-action
      with:
        target: 'check'